In [5]:
import csv

import pandas as pd  
import numpy as np  

# Đọc dữ liệu từ file CSV  
df = pd.read_csv(r'D:\17A1KHDL\LAB2\Data\diem_hoc_phan.csv')  

# Chuyển đổi dữ liệu thành một list  
data_list = df[['HP 1', 'HP 2', 'HP 3']].values.tolist()  

# Chuyển đổi list thành mảng NumPy  
data_array = np.array(data_list)  

print(data_array)



[[3.04 3.39 6.7 ]
 [5.8  6.41 6.62]
 [2.59 3.57 9.16]
 [3.81 8.78 9.24]
 [8.91 9.64 6.39]
 [3.23 4.72 6.17]
 [2.35 3.29 6.89]
 [2.48 3.81 4.84]
 [3.23 2.61 4.52]
 [7.02 9.01 9.15]
 [2.29 4.48 5.51]
 [3.51 7.19 5.13]
 [6.74 7.78 6.19]
 [9.86 4.64 3.33]
 [8.04 5.12 4.77]
 [2.74 8.88 5.8 ]
 [3.04 6.88 3.91]
 [5.87 4.41 8.84]
 [8.46 2.63 4.91]
 [3.74 6.71 3.44]
 [5.67 8.05 6.03]
 [8.12 2.46 3.87]
 [9.4  5.31 5.13]
 [3.91 5.09 8.82]
 [4.26 5.78 8.14]
 [4.41 2.66 5.4 ]
 [3.23 8.3  8.64]
 [9.25 8.29 9.1 ]
 [6.08 2.67 6.39]
 [3.85 7.71 5.75]]


In [6]:
def convert_grade(point):  
    if point >= 8.5:  
        return 'A'  
    elif point >= 8.0:  
        return 'B+'  
    elif point >= 7.0:  
        return 'B'  
    elif point >= 6.5:  
        return 'C+'  
    elif point >= 5.5:  
        return 'C'  
    elif point >= 5.0:  
        return 'D+'  
    elif point >= 4.0:  
        return 'D'  
    else:  
        return 'F'  

# Áp dụng hàm qui đổi cho từng điểm số trong mảng  
grades_array = np.vectorize(convert_grade)(data_array)  

print(grades_array)

[['F' 'F' 'C+']
 ['C' 'C' 'C+']
 ['F' 'F' 'A']
 ['F' 'A' 'A']
 ['A' 'A' 'C']
 ['F' 'D' 'C']
 ['F' 'F' 'C+']
 ['F' 'F' 'D']
 ['F' 'F' 'D']
 ['B' 'A' 'A']
 ['F' 'D' 'C']
 ['F' 'B' 'D+']
 ['C+' 'B' 'C']
 ['A' 'D' 'F']
 ['B+' 'D+' 'D']
 ['F' 'A' 'C']
 ['F' 'C+' 'F']
 ['C' 'D' 'A']
 ['B+' 'F' 'D']
 ['F' 'C+' 'F']
 ['C' 'B+' 'C']
 ['B+' 'F' 'F']
 ['A' 'D+' 'D+']
 ['F' 'D+' 'A']
 ['D' 'C' 'B+']
 ['D' 'F' 'D+']
 ['F' 'B+' 'A']
 ['A' 'B+' 'A']
 ['C' 'F' 'C']
 ['F' 'B' 'C']]


In [7]:
# Tạo DataFrame riêng cho từng học phần  
hp1_scores = df['HP 1']  
hp2_scores = df['HP 2']  
hp3_scores = df['HP 3']

In [8]:
# Phân tích cho từng học phần  
def analyze_scores(scores):  
    total = np.sum(scores)  
    mean = np.mean(scores)  
    std_dev = np.std(scores)  
    
    return total, mean, std_dev  

hp1_analysis = analyze_scores(hp1_scores)  
hp2_analysis = analyze_scores(hp2_scores)  
hp3_analysis = analyze_scores(hp3_scores)  

print("HP 1 - Tổng:", hp1_analysis[0], "Trung bình:", hp1_analysis[1], "Độ lệch chuẩn:", hp1_analysis[2])  
print("HP 2 - Tổng:", hp2_analysis[0], "Trung bình:", hp2_analysis[1], "Độ lệch chuẩn:", hp2_analysis[2])  
print("HP 3 - Tổng:", hp3_analysis[0], "Trung bình:", hp3_analysis[1], "Độ lệch chuẩn:", hp3_analysis[2])

HP 1 - Tổng: 154.92999999999998 Trung bình: 5.1643333333333326 Độ lệch chuẩn: 2.4078519934211533
HP 2 - Tổng: 170.27 Trung bình: 5.675666666666667 Độ lệch chuẩn: 2.2494765070023637
HP 3 - Tổng: 188.78 Trung bình: 6.292666666666666 Độ lệch chuẩn: 1.8082292135923723


In [9]:
# Đếm số lượng sinh viên đạt từng loại điểm chữ  
def count_grades(grades):  
    counts = {grade: 0 for grade in ['A', 'B+', 'B', 'C+', 'C', 'D+', 'D', 'F']}  
    
    for grade in grades.flatten():  
        if grade in counts:  
            counts[grade] += 1  
    
    return counts  

grade_counts = count_grades(grades_array)  
print("Số lượng sinh viên theo từng loại điểm:")  
print(grade_counts)

Số lượng sinh viên theo từng loại điểm:
{'A': 15, 'B+': 7, 'B': 4, 'C+': 6, 'C': 14, 'D+': 6, 'D': 10, 'F': 28}
